/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as DevocionalRouteImport } from './routes/devocional'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as PecadoRouteImport } from './routes/pecado'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TempoComDeusRouteImport } from './routes/tempo-com-deus'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const DevocionalRoute = DevocionalRouteImport.update({
  id: '/devocional',
  path: '/devocional',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const PecadoRoute = PecadoRouteImport.update({
  id: '/pecado',
  path: '/pecado',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TempoComDeusRoute = TempoComDeusRouteImport.update({
  id: '/tempo-com-deus',
  path: '/tempo-com-deus',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblia': typeof BibliaRoute
  '/devocional': typeof DevocionalRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRoute
  '/pecado': typeof PecadoRoute
  '/plano': typeof PlanoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tempo-com-deus': typeof TempoComDeusRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblia': typeof BibliaRoute
  '/devocional': typeof DevocionalRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRoute
  '/pecado': typeof PecadoRoute
  '/plano': typeof PlanoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tempo-com-deus': typeof TempoComDeusRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblia': typeof BibliaRoute
  '/devocional': typeof DevocionalRoute
  '/login': typeof LoginRoute
  '/oferta': typeof OfertaRoute
  '/pecado': typeof PecadoRoute
  '/plano': typeof PlanoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tempo-com-deus': typeof TempoComDeusRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/biblia'
    | '/devocional'
    | '/login'
    | '/oferta'
    | '/pecado'
    | '/plano'
    | '/reset-password'
    | '/tempo-com-deus'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/biblia'
    | '/devocional'
    | '/login'
    | '/oferta'
    | '/pecado'
    | '/plano'
    | '/reset-password'
    | '/tempo-com-deus'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/biblia'
    | '/devocional'
    | '/login'
    | '/oferta'
    | '/pecado'
    | '/plano'
    | '/reset-password'
    | '/tempo-com-deus'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BibliaRoute: typeof BibliaRoute
  DevocionalRoute: typeof DevocionalRoute
  LoginRoute: typeof LoginRoute
  OfertaRoute: typeof OfertaRoute
  PecadoRoute: typeof PecadoRoute
  PlanoRoute: typeof PlanoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TempoComDeusRoute: typeof TempoComDeusRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devocional': {
      id: '/devocional'
      path: '/devocional'
      fullPath: '/devocional'
      preLoaderRoute: typeof DevocionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecado': {
      id: '/pecado'
      path: '/pecado'
      fullPath: '/pecado'
      preLoaderRoute: typeof PecadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempo-com-deus': {
      id: '/tempo-com-deus'
      path: '/tempo-com-deus'
      fullPath: '/tempo-com-deus'
      preLoaderRoute: typeof TempoComDeusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BibliaRoute: BibliaRoute,
  DevocionalRoute: DevocionalRoute,
  LoginRoute: LoginRoute,
  OfertaRoute: OfertaRoute,
  PecadoRoute: PecadoRoute,
  PlanoRoute: PlanoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TempoComDeusRoute: TempoComDeusRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
