REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
DROP POLICY "Read published videos" ON public.videos;
CREATE POLICY "Anon reads published videos" ON public.videos FOR SELECT TO anon USING (published);
CREATE POLICY "Users read videos" ON public.videos FOR SELECT TO authenticated USING (published OR public.has_role(auth.uid(),'admin'));
DROP POLICY "Read published announcements" ON public.announcements;
CREATE POLICY "Anon reads published announcements" ON public.announcements FOR SELECT TO anon USING (published);
CREATE POLICY "Users read announcements" ON public.announcements FOR SELECT TO authenticated USING (published OR public.has_role(auth.uid(),'admin'));
DROP POLICY "Admins manage videos" ON public.videos;
CREATE POLICY "Admins insert videos" ON public.videos FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins update videos" ON public.videos FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins delete videos" ON public.videos FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));
DROP POLICY "Admins manage announcements" ON public.announcements;
CREATE POLICY "Admins insert announcements" ON public.announcements FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins update announcements" ON public.announcements FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins delete announcements" ON public.announcements FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));
DROP POLICY "Admins manage devotionals" ON public.devotional_overrides;
CREATE POLICY "Admins insert devotionals" ON public.devotional_overrides FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins update devotionals" ON public.devotional_overrides FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE POLICY "Admins delete devotionals" ON public.devotional_overrides FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));