// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://youuzhblzuqtwwtqhrgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvdXV6aGJsenVxdHd3dHFocmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEyNDYxNzYsImV4cCI6MjEwNjgyMjE3Nn0.YrrlsEdejReb_pRaEt8HuDBmBPj87eVffvj8zHfOZZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});